---
- name: check required variables
  fail: msg="{{ item }} is not defined"
  when: item not in vars
  with_items: "{{ samba_cl_required_vars }}"

- name: install samba client packages
  apt_rpm:
    pkg: "{{samba_cl_packages | join(',')}}"
    state: installed
    update_cache: yes
  when: samba_cl_packages | length > 0
  notify: restart samba

- name: link ldb directory
  file:
    src: /usr/lib64/ldb/modules/ldb
    dest: /usr/lib64/samba/ldb
    state: link

- name: create /etc/krb5.conf
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- name: disble resolv.conf management by NM
  lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    regexp: '^dns='
    line: 'dns=none'
    backrefs: yes
    state: present
  register: nm_conf_is
  notify: restart networkmanager

- name: Add line if not configured
  lineinfile:
    state   : present
    dest    : /etc/NetworkManager/NetworkManager.conf
    line    : 'dns=none'
    regexp  : ''
    insertafter: EOF
  when: nm_conf_is.changed == false
  notify: restart networkmanager

- name: enable eth0
  lineinfile:
    path: /etc/net/ifaces/eth0/options
    regexp: '^DISABLED='
    line: 'DISABLED=no'
    backrefs: yes
    state: present
  register: net_conf_is
  changed_when: net_conf_is.changed
  notify: restart network

- name: set master as an only nameserver
  template:
    src: resolv.conf.j2
    dest: /etc/net/ifaces/eth0/resolv.conf
  notify: restart network

- meta: flush_handlers

- name: update resolver
  shell: resolvconf -d NetworkManager; resolvconf -u
  changed_when: false

- name: join to the domain
  shell: system-auth write ad {{samba_realm|upper}} {{inventory_hostname_short}} {{samba_domain|upper}} 'Administrator' '{{samba_admin_pass}}'
