---

- name: purge other resolv.conf`s
  command: >
    find /etc/net/ifaces -name resolv.conf -delete
  register: res
  changed when: res.rc == 0
  failed_when: false

- name: set master DC as the 1st nameserver
  template:
    src: resolv.conf.j2
    dest: /etc/net/ifaces/lo/resolv.conf

- name: black magic
  shell: update_chrooted all
  changed_when: false

- name: restart network service
  service:
    name: network
    state: restarted
