---
- name: remove conflict samba server packages
  shell: "apt-get remove -y nss-ldapd nscd"

- name: Stop BIND9 daemon
  service:
    name: bind
    enabled: false
    state: stopped
  register: cmd_result
  failed_when: "cmd_result|failed and ('find' not in cmd_result.msg and 'found' not in cmd_result.msg)"

- name: Check if conflicting processes are running
  shell: |
    lsof -i -P -n | grep "TCP .*:\(53\|389\|88\) (LISTEN)" | cut -f1 -d ' ' | uniq
  register: services

- name: Stop conflicting services
  shell: "pkill {{ item }}"
  with_items: "{{ services.stdout_lines }}"
