---
- name: remove conflict samba server packages
  shell: "apt-get remove -y nss-ldapd nscd"

- name: Stop BIND9 daemon
  service:
    name: bind
    enabled: false
    state: stopped
  register: cmd_result
  failed_when: "cmd_result|failed and ('find' not in cmd_result.msg and 'found' not in cmd_result.msg)"

- name: Check if conflicting processes are running
  shell: |
    lsof -i UDP:53 -i TCP:445 -i TCP:389 -i UDP:88 -F f | grep ^p | sed 's/^p//' | uniq
  register: conflict_processes

- name: Stop conflicting services
  shell: "kill {{ item }}"
  with_items: "{{ conflict_processes.stdout_lines }}"
